# Project information
site_name: Knowledge Base
site_description: 'Sammlung von Tipps und Tricks rund um unsere Software-Produkte.'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.kb.stueber.de'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.kb.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Überblick: index.md
- MAGELLAN:
  - Installation:
    - Erste Schritte: magellan/erste-schritte-in-magellan.md
    - Silent-Mode-Parameter: sonstiges/silentmode.md
    - Citrix: magellan/citrixinstallation.md
    - Linux: magellan/admin.linux.md
    - Logdatei: magellan/log.md
    - Pathsdatei: magellan/pathsdatei.md
    - Voraussetzungen (Hardware): magellan/system-requirements.md
    - Sicherung per Taskplaner: magellan/admin_sicherung.taskplaner.md
    - V9 Neuer Serverrechner: magellan/admin-serverumzug9.md
    - V7 Neuer Serverrechner: magellan/admin-serverumzug7.md
    - V6 Neuer Serverrechner: magellan/admin-serverumzug6.md
    - Zwei Datenbanken auf einem Server: magellan/2_db_ein_server.md
  - Schulverwaltung:
    - ABS Neues Halbjahr, neues Schuljahr: magellan/neues-halbjahr-neues-schuljahr.md
    - BBS Neues Halbjahr, neues Schuljahr: magellan/bbs-neues-halbjahr-neues-schuljahr-was-ist-zu-tun.md
    - CSV-Dateien mit Texttrennzeichen speichern: magellan/import-csvdateien.md
    - Fachlehrer den Schülerfachdaten zuweisen: magellan/mag_lehrer_nachtraeglich_zuweisen.md
    - Fachwahlkarte: magellan/fachwahl.md
    - Jahrgangsübergreifende Klassen: magellan/jahrgangsubergreifende-klassen-in-magellan.md
    - Fächer abgleichen mit daVinci: magellan/abgleich.stammdaten.md
    - Abgleich mit Untis: magellan/import_mag.untis.md
    - PDF-Skalierung aus CR: magellan/skalierung.cr.md
    - PLZ und Gemeinden aktualisieren: magellan/plz.aktualisieren.md
    - Positionen für den Zeugnisdruck nachträglich zuweisen: magellan/mag_positionen_nachpflegen.md
    - Probleme mit dem PDF-Export: magellan/pdf_fehler.md
    - Schlüsselverzeichnisse hinter Feldern: magellan/Schluesselverzeichnisse.md
    - Tastaturkürzel: magellan/Shortcuts_Tastaturkuerzel.md
  - Serienmail:
    - Interface nicht unterstützt: magellan/interface.md
    - Mapi-Fehlermeldung: magellan/mapi.md
    - Welcher Maiclient wird aufgerufen: sonstiges/mapi2.md
  - Druck, Seriendruck:
    - Makrospeicher konnte nicht geöffnet werden: magellan/makrospeicher.md
    - Umlaute in der Druckvorschau: magellan/umlaute_druck.md
    - Word stellt Umlaute nicht korrekt dar: magellan/umlaute.md
  - Bibliothek:
    - Optimale Hardware: bib/Bib_Hardware.md
    - OPAC Unterstützung: bib/bib.opac.md
- Crystal Reports:
  - Allgemein:
    - Bewerberberichte mit Sorgeberechtigten: cr/sb.md
    - Barcodes: cr/barcode.md
    - Berichte für V7/V8 anpassen: cr/berichte_fuer_7_anpassen.md
    - Drucksortierung der Datensätze in Berichten: cr/drucksortierung.md
    - Empfohlene Verknüpfungen: cr/verknuepfung.md
    - Es werden mehr als die ausgewählten Datensätze gezeigt: cr/zuviele.datensaetze.md
    - Felder im Bericht aktualisieren: cr/felder-im-bericht-aktualisieren.md
    - Fächer mit hochgestellter Ziffer für einen Verweis auf eine Fußnote: cr/cr-hochgestellt.md
    - Join-Typ kann nicht geändert werden: cr/auto.verknuepfung.md
    - Tabelle '' nicht gefunden: cr/cr-tabelle.nicht.gefunden.md
    - Method not found...: cr/meldung.md
    - ODBC-Anbindung unter Windows 64 bit: cr/cr-odbc-64bit.md
    - Personalisieren von Zeugnisbemerkungen: cr/cr-zeugnisbemerkungen-personalisieren.md
    - Sorgeberechtigte und Nebenschüler: cr/nebenschueler.sb.md
    - Sortierung oder Gruppierung: cr/sortierung-und-gruppierung.md
    - Standarddrucker für CR-Berichte: cr/cr-drucker.md
    - Vor- und Nachname in Berichten: cr/cr-vor-und-nachname.md
  - Archiv:
    - Änderung in der Tabelle SchuelerAusbildung: cr/schuelerausbildung.md
    - Fehler in Crystal Reports 9: cr/CR9_Fehler.md
- DAVINCI:
  - Allgemein:
    - Silent-Mode-Parameter: sonstiges/silentmode.md
    - Umzug auf einen neuen Server: sonstiges/umzug.auf.neuen.server.md
    - Schuljahreswechsel: sonstiges/schuljahreswechsel.md
    - Plandatei aufräumen: sonstiges/plandatei.aufraeumen.md
    - Pathsdatei: sonstiges/pathsdatei.md
  - Infoserver:
    - Eigene CSS-Datei für CONFIRE SHOWTIME-Vertretungsapp: infoserver/css.showtime.md
    - Einrichtung: infoserver/einrichtung.md
    - Fachfarben in der WEBBOX und APP: infoserver/farben.md
    - HTML-Vorlagen mit "local" oder mit "main"?: infoserver/htmlvorlagen.md
    - HTTPS Protokoll: https-protokoll.md
    - Infoserver und Webbox aktualisieren: infoserver/infoserver-und-webbox-aktualisieren.md
    - Rechte und Benutzer für die WEBBOX: rechte-und-benutzer-fur-die-webbox.md
    - Vertretungsliste soll flippen: infoserver/vertretungsliste-flippen.md
    - Webbox-Vertretungsliste per Browser für E-Boards: infoserver/webboxvertretungsliste.per.browser.md
    - Webbox-Vertretungspläne für Confire Showtime: infoserver/webbox.fuer.showtime.md
  - Kalender:
    - Google-Token löschen: kalender/google.token.loeschen.md
  - Stundenplan:
    - Berechnungskonzepte in daVinci: stundenplan/berechnungskonzepte.md
    - Verrechnungsarten: stundenplan\verrechnungsarten.md
    - Korrespondierende Pläne: stundenplan/korrespond.planfenster.md
    - Lehrer-Zeitkonten: stundenplan/lehrer-zeitkonten.md
    - Sortierung Stammdatenfenster: stundenplan/sort.stammdaten.md
    - Stammdaten importieren: stundenplan/stammdaten-importieren.md
    - Welcher Maiclient wird aufgerufen: sonstiges/mapi2.md
    - Zeitschienen in DAVINCI: stundenplan/zeitschienen-in-davinci.md
  - Vertretungsplan:
    - Veröffentlichung: veroeffentlichung\veroeffentlichung.md
  - Explorer:
    - Plandateienstruktur und Rechtevergabe: explorer/plandateienstruktur.im.explorer.md
  - Look:
    - Automatischer Start voreingestellten Ansicht: look/autostart.md
  - Statistik:
    - WinLD und ASV: statistik\winld_asv.md
- ENBREA:
    - Welche Daten benötigen wir?: enbrea/daten.md
- Support:
    - Skriptdatei tauschen: support/skript_tauschen.md
    - Skripteditor ausführen: support/skripteditor.md
    - Ticketaccount anlegen: support/ticket_anlegen.md
    - Ticket anlegen: support/ticketsystem.md

  